name: Build Ledtrix.zip

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make zip
      - name: Set VERSION from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Build artifacts
        run: |
          make VERSION=${{ env.VERSION }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ledtrix artifacts
          path: |
            ledtrix-${{ env.VERSION }}.zip
            ledtrix-${{ env.VERSION }}.tar.gz
          if-no-files-found: error
      - name: Clean up build artifacts
        run: |
          make clean

