name: Build ledtrix

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make zip
      - name: Build artifacts
        run: |
          make VERSION=${{ github.ref_name }}
      - name: Upload ledtrix.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: ledtrix-${{ github.ref_name }}.zip
          path: ledtrix-${{ github.ref_name }}.zip
          if-no-files-found: error
      - name: Upload ledtrix.tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: ledtrix-${{ github.ref_name }}.tar.gz
          path: ledtrix-${{ github.ref_name }}.tar.gz
          if-no-files-found: error
      - name: Clean up build artifacts
        run: |
          make clean

  release:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download ledtrix.zip artifact
          uses: actions/download-artifact@v4
          with:
            name: ledtrix-${{ github.event.release.tag_name }}.zip
        - name: Download ledtrix.tar.gz artifact
          uses: actions/download-artifact@v4
          with:
            name: ledtrix-${{ github.event.release.tag_name }}.tar.gz
        - name: Upload ledtrix.zip to release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ledtrix-${{ github.event.release.tag_name }}.zip
            asset_name: ledtrix-${{ github.event.release.tag_name }}.zip
            asset_content_type: application/zip
        - name: Upload ledtrix.tar.gz to release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ledtrix-${{ github.event.release.tag_name }}.tar.gz
            asset_name: ledtrix-${{ github.event.release.tag_name }}.tar.gz
            asset_content_type: application/gzip

